# Generated by Django 2.0.2 on 2018-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name of an item', max_length=40)),
                ('summary', models.TextField(help_text='Enter a brief description of an item', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chocs_images/%Y/%m/%D')),
                ('status', models.CharField(blank=True, choices=[('a', 'Available'), ('d', 'Under development'), ('o', 'Out of stock'), ('i', 'In production')], default='d', help_text='Item availability', max_length=1)),
            ],
        ),
    ]
