# Generated by Django 2.0.2 on 2018-02-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0002_auto_20180228_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='candy_item',
            field=models.ManyToManyField(blank=True, help_text='Select a candy for this set', to='chocs.Candy'),
        ),
    ]
