# Generated by Django 2.0.2 on 2018-03-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0004_auto_20180228_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter a description of the item', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.CharField(help_text='enter a height in cm.', max_length=10)),
                ('width', models.CharField(help_text='enter a height in cm.', max_length=10)),
                ('price', models.CharField(help_text='enter a price here.', max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='sets',
            name='price',
            field=models.CharField(blank=True, help_text='Entrer a price here', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='size',
            field=models.ManyToManyField(blank=True, to='chocs.Size'),
        ),
    ]
