# Generated by Django 2.0.2 on 2018-03-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0005_auto_20180301_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bar',
            name='size',
        ),
        migrations.AddField(
            model_name='bar',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocs.Size'),
        ),
    ]
