# Generated by Django 2.0.2 on 2018-03-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0006_auto_20180301_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bars_images'),
        ),
    ]
