# Generated by Django 2.0.2 on 2018-03-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0007_bar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='weight',
            field=models.CharField(blank=True, help_text='Enter a weight in grams here', max_length=4, null=True),
        ),
    ]
