# Generated by Django 2.0.2 on 2018-03-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0011_auto_20180303_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='product_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
