# Generated by Django 2.0.2 on 2018-03-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0012_auto_20180303_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='Entrer a price here', max_length=5, null=True),
        ),
    ]
