# Generated by Django 2.0.2 on 2018-03-04 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0013_auto_20180303_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chocs.Sets'),
        ),
    ]
