# Generated by Django 2.0.1 on 2018-03-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0015_remove_productinbasket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sets',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='Entrer a price here', null=True),
        ),
    ]
