# Generated by Django 2.0.1 on 2018-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chocs', '0016_auto_20180330_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
